name: twitch-cv2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - pip=21.2.4
  - pip:
    - streamlink==3.0.3
    - pytesseract==0.3.8
    - playsound==1.3.0
    - PyObjC==8.1